

CC = gcc

ifeq ($(MACHINE), x64)
CFLAGS = -DCONFIG_64 -Wall -W -O2 -fomit-frame-pointer -s
endif

ifeq ($(MACHINE), ansi64)
CFLAGS = -DCONFIG_64 -DHAVE_UINT128_T -DTEST_UINT128_T -Wall -W -O2 -fomit-frame-pointer -s
endif

ifeq ($(MACHINE), ansi64c32)
CFLAGS = -DCONFIG_32 -DANSI -Wall -W -O2 -fomit-frame-pointer -s
endif

ifeq ($(MACHINE), ppro)
CFLAGS = -m32 -DCONFIG_32 -DPPRO -Wall -W -O2 -fomit-frame-pointer -s
endif

ifeq ($(MACHINE), ansi32)
CFLAGS = -m32 -DCONFIG_32 -DANSI -Wall -W -O2 -fomit-frame-pointer -s
endif

ifeq ($(MACHINE), ansi-legacy)
CFLAGS = -DCONFIG_32 -DANSI -DLEGACY_COMPILER -Wall -W -O2 -fomit-frame-pointer -s
endif


GMPINC = -I/usr/include -I/usr/local/include
GMPLIBS = -L/usr/lib -L/usr/local/lib
SRCDIR = ../../../../Modules/cdecimal
INC= -I../../../../ -I$(SRCDIR)
OBJDIR = obj
OBJS = $(OBJDIR)/basearith.o    $(OBJDIR)/context.o $(OBJDIR)/constants.o \
       $(OBJDIR)/convolute.o    $(OBJDIR)/crt.o     $(OBJDIR)/mpdecimal.o \
       $(OBJDIR)/difradix2.o    $(OBJDIR)/error.o   $(OBJDIR)/fnt.o \
       $(OBJDIR)/fourstep.o     $(OBJDIR)/io.o      $(OBJDIR)/memory.o \
       $(OBJDIR)/numbertheory.o $(OBJDIR)/sixstep.o $(OBJDIR)/transpose.o \
       $(OBJDIR)/transpose3.o


default: runtest karatsuba_fnt karatsuba_fnt2 ppro_mulmod test_transpose
gmp:     runtest karatsuba_fnt karatsuba_fnt2 ppro_mulmod test_transpose \
         mpd_mpz_add mpd_mpz_divmod mpd_mpz_mul mpd_mpz_sub


runtest: Makefile $(OBJDIR)/runtest.o $(OBJS)
	$(CC) $(CFLAGS) -o runtest $(OBJDIR)/runtest.o $(OBJS) -lm
karatsuba_fnt: Makefile $(OBJDIR)/karatsuba_fnt.o $(OBJS)
	$(CC) $(CFLAGS) -o karatsuba_fnt $(OBJDIR)/karatsuba_fnt.o $(OBJS) -lm
karatsuba_fnt2: Makefile $(OBJDIR)/karatsuba_fnt2.o $(OBJS)
	$(CC) $(CFLAGS) -o karatsuba_fnt2 $(OBJDIR)/karatsuba_fnt2.o $(OBJS) -lm
ppro_mulmod: Makefile $(OBJDIR)/ppro_mulmod.o $(OBJS)
	$(CC) $(CFLAGS) -o ppro_mulmod $(OBJDIR)/ppro_mulmod.o $(OBJS) -lm
test_transpose: Makefile $(OBJDIR)/test_transpose.o $(OBJS)
	$(CC) $(CFLAGS) -o test_transpose $(OBJDIR)/test_transpose.o $(OBJS) -lm


mpd_mpz_add: Makefile $(OBJDIR)/mpd_mpz_add.o $(OBJS)
	$(CC) $(GMPLIBS) $(CFLAGS) -o mpd_mpz_add $(OBJDIR)/mpd_mpz_add.o  $(OBJS) -lm -lgmp
mpd_mpz_divmod: Makefile $(OBJDIR)/mpd_mpz_divmod.o $(OBJS)
	$(CC) $(GMPLIBS) $(CFLAGS)  -o mpd_mpz_divmod $(OBJDIR)/mpd_mpz_divmod.o $(OBJS) -lm -lgmp
mpd_mpz_mul: Makefile $(OBJDIR)/mpd_mpz_mul.o $(OBJDIR)/mpd_mpz_divmod.o $(OBJS)
	$(CC) $(GMPLIBS) $(CFLAGS) -o mpd_mpz_mul $(OBJDIR)/mpd_mpz_divmod.o $(OBJS) -lm -lgmp
mpd_mpz_sub: Makefile $(OBJDIR)/mpd_mpz_sub.o $(OBJDIR)/mpd_mpz_divmod.o $(OBJS)
	$(CC) $(GMPLIBS) $(CFLAGS) -o mpd_mpz_sub $(OBJDIR)/mpd_mpz_sub.o $(OBJS) -lm -lgmp


# dectest
$(OBJDIR)/runtest.o:\
Makefile runtest.c $(SRCDIR)/io.h     $(SRCDIR)/mpdecimal.h $(SRCDIR)/memory.h \
                   $(SRCDIR)/mptest.h $(SRCDIR)/mptypes.h
	$(CC) $(INC) $(CFLAGS) -c runtest.c -o $(OBJDIR)/runtest.o

# extended tests
$(OBJDIR)/karatsuba_fnt.o:\
Makefile karatsuba_fnt.c $(SRCDIR)/mpdecimal.h  $(SRCDIR)/mptypes.h \
                         $(SRCDIR)/mptest.h
	$(CC) $(INC) $(CFLAGS) -c karatsuba_fnt.c -o $(OBJDIR)/karatsuba_fnt.o

$(OBJDIR)/karatsuba_fnt2.o:\
Makefile karatsuba_fnt2.c $(SRCDIR)/mpdecimal.h  $(SRCDIR)/mptypes.h \
                          $(SRCDIR)/mptest.h
	$(CC) $(INC) $(CFLAGS) -c karatsuba_fnt2.c -o $(OBJDIR)/karatsuba_fnt2.o

$(OBJDIR)/ppro_mulmod.o:\
Makefile ppro_mulmod.c $(SRCDIR)/mpdecimal.h    $(SRCDIR)/constants.h \
                       $(SRCDIR)/numbertheory.h $(SRCDIR)/mptypes.h \
                       $(SRCDIR)/mptest.h       $(SRCDIR)/umodarith.h \
                       $(SRCDIR)/typearith.h
	$(CC) $(INC) $(CFLAGS) -c ppro_mulmod.c -o $(OBJDIR)/ppro_mulmod.o

$(OBJDIR)/test_transpose.o:\
Makefile test_transpose.c $(SRCDIR)/bits.h      $(SRCDIR)/mpdecimal.h \
                          $(SRCDIR)/constants.h $(SRCDIR)/mptypes.h \
                          $(SRCDIR)/mptest.h    $(SRCDIR)/typearith.h \
                          $(SRCDIR)/transpose.h
	$(CC) $(INC) $(CFLAGS) -c test_transpose.c -o $(OBJDIR)/test_transpose.o

# tests against gmp
$(OBJDIR)/mpd_mpz_add.o:\
Makefile mpd_mpz_add.c $(SRCDIR)/mpdecimal.h $(SRCDIR)/mptypes.h
	$(CC) $(INC) $(GMPINC) $(CFLAGS) -c mpd_mpz_add.c -o $(OBJDIR)/mpd_mpz_add.o

$(OBJDIR)/mpd_mpz_divmod.o:\
Makefile mpd_mpz_divmod.c $(SRCDIR)/mpdecimal.h $(SRCDIR)/mptypes.h
	$(CC) $(INC) $(GMPINC) $(CFLAGS) -c mpd_mpz_divmod.c -o $(OBJDIR)/mpd_mpz_divmod.o

$(OBJDIR)/mpd_mpz_mul.o:\
Makefile mpd_mpz_mul.c $(SRCDIR)/mpdecimal.h $(SRCDIR)/mptypes.h
	$(CC) $(INC) $(GMPINC) $(CFLAGS) -c mpd_mpz_mul.c -o $(OBJDIR)/mpd_mpz_mul.o

$(OBJDIR)/mpd_mpz_sub.o:\
Makefile mpd_mpz_sub.c $(SRCDIR)/mpdecimal.h $(SRCDIR)/mptypes.h
	$(CC) $(INC) $(GMPINC) $(CFLAGS) -c mpd_mpz_sub.c -o $(OBJDIR)/mpd_mpz_sub.o


$(OBJDIR)/basearith.o:\
Makefile $(SRCDIR)/basearith.c $(SRCDIR)/constants.h $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/memory.h    $(SRCDIR)/typearith.h $(SRCDIR)/basearith.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/basearith.c -o $(OBJDIR)/basearith.o

$(OBJDIR)/constants.o:\
Makefile $(SRCDIR)/constants.c $(SRCDIR)/mpdecimal.h $(SRCDIR)/constants.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/constants.c -o $(OBJDIR)/constants.o

$(OBJDIR)/context.o:\
Makefile $(SRCDIR)/context.c $(SRCDIR)/mpdecimal.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/context.c -o $(OBJDIR)/context.o

$(OBJDIR)/convolute.o:\
Makefile $(SRCDIR)/convolute.c    $(SRCDIR)/bits.h      $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/constants.h    $(SRCDIR)/fnt.h       $(SRCDIR)/fourstep.h \
         $(SRCDIR)/numbertheory.h $(SRCDIR)/sixstep.h   $(SRCDIR)/umodarith.h \
         $(SRCDIR)/typearith.h    $(SRCDIR)/convolute.h $(SRCDIR)/vccompat.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/convolute.c -o $(OBJDIR)/convolute.o

$(OBJDIR)/crt.o:\
Makefile $(SRCDIR)/crt.c       $(SRCDIR)/mpdecimal.h $(SRCDIR)/numbertheory.h \
         $(SRCDIR)/constants.h $(SRCDIR)/umodarith.h $(SRCDIR)/typearith.h \
         $(SRCDIR)/crt.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/crt.c -o $(OBJDIR)/crt.o

$(OBJDIR)/difradix2.o:\
Makefile $(SRCDIR)/difradix2.c    $(SRCDIR)/bits.h      $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/numbertheory.h $(SRCDIR)/constants.h $(SRCDIR)/umodarith.h \
         $(SRCDIR)/typearith.h    $(SRCDIR)/difradix2.h $(SRCDIR)/vccompat.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/difradix2.c -o $(OBJDIR)/difradix2.o

$(OBJDIR)/error.o:\
Makefile $(SRCDIR)/error.c $(SRCDIR)/mpdecimal.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/error.c -o $(OBJDIR)/error.o

$(OBJDIR)/fnt.o:\
Makefile $(SRCDIR)/fnt.c       $(SRCDIR)/bits.h         $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/difradix2.h $(SRCDIR)/numbertheory.h $(SRCDIR)/constants.h \
         $(SRCDIR)/fnt.h       $(SRCDIR)/vccompat.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/fnt.c -o $(OBJDIR)/fnt.o

$(OBJDIR)/fourstep.o:\
Makefile $(SRCDIR)/fourstep.c  $(SRCDIR)/mpdecimal.h $(SRCDIR)/numbertheory.h \
         $(SRCDIR)/constants.h $(SRCDIR)/sixstep.h   $(SRCDIR)/transpose.h \
         $(SRCDIR)/umodarith.h $(SRCDIR)/typearith.h $(SRCDIR)/fourstep.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/fourstep.c -o $(OBJDIR)/fourstep.o

$(OBJDIR)/io.o:\
Makefile $(SRCDIR)/io.c        $(SRCDIR)/bits.h   $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/constants.h $(SRCDIR)/memory.h $(SRCDIR)/typearith.h \
         $(SRCDIR)/io.h        $(SRCDIR)/vccompat.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/io.c -o $(OBJDIR)/io.o

$(OBJDIR)/memory.o:\
Makefile $(SRCDIR)/memory.c $(SRCDIR)/mpdecimal.h $(SRCDIR)/typearith.h \
         $(SRCDIR)/memory.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/memory.c -o $(OBJDIR)/memory.o

$(OBJDIR)/mpdecimal.o:\
Makefile $(SRCDIR)/mpdecimal.c $(SRCDIR)/basearith.h $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/typearith.h $(SRCDIR)/bits.h      $(SRCDIR)/convolute.h \
         $(SRCDIR)/crt.h       $(SRCDIR)/memory.h    $(SRCDIR)/umodarith.h \
         $(SRCDIR)/constants.h $(SRCDIR)/mptypes.h   $(SRCDIR)/vccompat.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/mpdecimal.c -o $(OBJDIR)/mpdecimal.o

$(OBJDIR)/numbertheory.o:\
Makefile $(SRCDIR)/numbertheory.c $(SRCDIR)/bits.h      $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/umodarith.h    $(SRCDIR)/constants.h $(SRCDIR)/typearith.h \
         $(SRCDIR)/numbertheory.h $(SRCDIR)/vccompat.h 
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/numbertheory.c -o $(OBJDIR)/numbertheory.o

$(OBJDIR)/sixstep.o:\
Makefile $(SRCDIR)/sixstep.c   $(SRCDIR)/bits.h         $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/difradix2.h $(SRCDIR)/numbertheory.h $(SRCDIR)/constants.h \
         $(SRCDIR)/mptypes.h   $(SRCDIR)/transpose.h    $(SRCDIR)/umodarith.h \
         $(SRCDIR)/typearith.h $(SRCDIR)/sixstep.h      $(SRCDIR)/vccompat.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/sixstep.c -o $(OBJDIR)/sixstep.o

$(OBJDIR)/transpose.o:\
Makefile $(SRCDIR)/transpose.c $(SRCDIR)/bits.h      $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/constants.h $(SRCDIR)/typearith.h $(SRCDIR)/transpose.h \
         $(SRCDIR)/vccompat.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/transpose.c -o $(OBJDIR)/transpose.o

$(OBJDIR)/transpose3.o:\
Makefile $(SRCDIR)/transpose3.c $(SRCDIR)/bits.h      $(SRCDIR)/mpdecimal.h \
         $(SRCDIR)/constants.h  $(SRCDIR)/typearith.h $(SRCDIR)/transpose.h \
         $(SRCDIR)/vccompat.h
	$(CC) $(INC) $(CFLAGS) -c $(SRCDIR)/transpose3.c -o $(OBJDIR)/transpose3.o


FORCE:

clean: FORCE
	rm -f $(OBJDIR)/*.o  runtest karatsuba_fnt karatsuba_fnt2 ppro_mulmod \
        test_transpose mpd_mpz_add mpd_mpz_divmod mpd_mpz_mul mpd_mpz_sub



